# Generated by Django 4.2.30 on 2026-10-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_accion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'acciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'asistencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cajas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionCobranza',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('dia_limite_pago', models.IntegerField()),
                ('recargo_mora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'configuracion_cobranza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cooperativa', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('nit', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'configuracion_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('metros_cubicos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_calculo', models.DateTimeField()),
            ],
            options={
                'db_table': 'consumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleDeudas',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_deudas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deudas',
            fields=[
                ('id_deuda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'deudas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id_lectura', models.AutoField(primary_key=True, serialize=False)),
                ('lectura_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lectura_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'lecturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidores',
            fields=[
                ('id_medidor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_medidor', models.CharField(max_length=50, unique=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('lectura_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'medidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_movimiento', models.DateTimeField()),
                ('tipo', models.CharField(max_length=20)),
                ('concepto', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'movimientos_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'periodos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangosTarifa',
            fields=[
                ('id_rango', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_desde', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumo_hasta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_excedente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rangos_tarifa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_socio', models.CharField(max_length=30, unique=True)),
                ('ci', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_afiliacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'socios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('consumo_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tarifas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
